# Generated by Django 5.2.8 on 2026-06-30 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_spotasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='spotwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='spotwallet_balance_non_negative'),
        ),
    ]
