# Generated by Django 5.2.8 on 2026-06-30 19:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureswallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='futureswallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='futures_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='futureswallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='futureswallet_balance_non_negative'),
        ),
    ]
